# Generated by Django 3.2.7 on 2021-09-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210926_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tag',
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('pending', 'Pending')], max_length=200, null=True),
        ),
    ]
