# Generated by Django 3.2.7 on 2021-10-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211014_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('out for delivery', 'Out for delivery'), ('pending', 'Pending'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('outdoor', 'Outdoor'), ('indore', 'Indore')], max_length=200, null=True),
        ),
    ]
